### ISSUE TITLE
项目并发问题

### ISSUE THREAD

**Issue by hezkvectory-yu** [solq360/common#1]
当我在
![image](https://cloud.githubusercontent.com/assets/8772541/15316716/c912ed96-1c50-11e6-945b-640e18558178.png)
这改成1000时，客户端同时启动两个，报如下错误，是哪里出问题

org.son.chat.common.net.exception.CoderException: 未找到编/解码处理器 
    at org.son.chat.common.net.core.socket.impl.AbstractISocketChannel.doRead(AbstractISocketChannel.java:152)
    at org.son.chat.common.net.core.socket.impl.SocketPool.handle(SocketPool.java:177)
    at org.son.chat.common.net.core.socket.impl.SocketPool.processKeys(SocketPool.java:91)
    at org.son.chat.common.net.core.socket.impl.SocketPool.processNio(SocketPool.java:83)
    at org.son.chat.common.net.core.socket.impl.SocketPool.run(SocketPool.java:238)
    at java.lang.Thread.run(Thread.java:722)

**Comment by solq360** [comment]
不好意思，现在没时间做这个了
